apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: krnmalde/final:nodek4
        ports:
        - containerPort: 3000
        # env:
        # - name: MONGO_URL
        #   value: mongodb://admin:password@mongodb
        

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
spec:
  type: LoadBalancer
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      
      